version: "3.7"

services:

  flask-container:
    build: ./flask-container
    container_name: flask-container
    restart: always
    network_mode: bridge
    environment:
      - APP_NAME=Media Grab Web app
    expose:
      - 80

  nginx-container:
    build: ./nginx-container
    container_name: nginx-container
    restart: always
    network_mode: bridge
    depends_on:
      - flask-container
    ports:
      - "5000:80"

