version: "3.7"

services:

  flask-container:
    build: ./flask-container
    container_name: flask-container
    restart: always
    links:
      - nginx-container
    environment:
      - APP_NAME=Media Grab Web app
      - MEDIA_INDEX_FILE_LOCATION=/tmp/media_grab/data/MediaIndex.json
      - MEDIA_GRAB_DIRECTORY=/tmp/media_grab
    volumes:
      - type: bind
        source: ../media_grab
        target: /tmp/media_grab
        volume:
          nocopy: true
    expose:
      - 8080

  nginx-container:
    build: ./nginx-container
    container_name: nginx-container
    restart: always
    ports:
      - "5000:8080"

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24
